const express = require("express")
const router = express.Router()
const Joi = require("joi")
const Jwt = require("jsonwebtoken")
const bcrypt = require("bcryptjs")

const users = require("../model/userModel")
const validateWith = require("../middleware/validation")

/*
  ---> A schema to check login email and password
*/

const schema = {
  email: Joi.string().email().required(),
  password: Joi.string().required().min(6),
}

/*
  ---> Handle Login
  1. Check the the values of the form (see middleware/validation.js)
  2. Checks database for email and password. But if does not match, returns an error.
  3. If email and password matches, then a token is generated by jsonwebtoken
  4. Finally, the token is sent back to the user, in the frontend
*/

router.post("/", validateWith(schema), async (req, res) => {
  const { email, password } = req.body

  const user = await users.findOne({ email })
  const decrytedPassword = await bcrypt.compare(password, user.password)

  //   {
  //     "images": [
  //         {
  //             "fileName": "http://192.168.43.233:9000/assets/9ccd61c1a60b58af5b7feee7ec8ce443_full.jpg"
  //         }
  //     ],
  //     "_id": "6033763b8fd69f03805423cb",
  //     "name": "Bonaventure",
  //     "email": "bona@gmail.com",
  //     "password": "$2a$10$tDApLiSu6kEfVRbgJv1Mhuhg834ClcfFIuqrYwyyjfTvdJ2UbKUsK",
  //     "reviews": [],
  //     "createdAt": "2021-02-22T09:15:39.741Z",
  //     "updatedAt": "2021-02-23T17:19:04.664Z",
  //     "__v": 32,
  //     "phoneNumber": "+254524455854",
  //     "location": "nando"
  // }

  if (user && decrytedPassword === true) {
    const token = Jwt.sign(
      {
        userId: user._id,
        name: user.name,
        email,
        phoneNumber: user.phoneNumber,
        location: user.location,
        images: user.images,
      },
      "jwtPrivateKey"
    )
    res.send(token)
  } else {
    res.status(400).send({
      error: "Password or email is incorrect",
    })
  }
})

module.exports = router
